name: vbuss
description: "Bus tracking serive for VIT Bhopal University"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  http: ^1.3.0
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  flutter_svg: ^2.0.7
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  flutter_sound: ^9.2.13
  audioplayers: ^5.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - icons/condriv-final.svg
    - icons/studemp-final.svg
    - icons/google.svg
    - assets/images/google_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
